package v2

// CodeTemplate ...
const CodeTemplate = `
// Code generated by code generator. DO NOT EDIT.

package {{.PackageName}}

` + ImportsTemplate + `

` + ConstantsTemplate + `

` + SchemaStructsTemplate + `

` + QueryBuilderTemplate + `

` + ScanBuilderTemplate + `

` + CrudPutTemplate + `

` + CrudUpdateTemplate + `

` + CrudDeleteTemplate + `

` + CrudOther + `

` + UtilityFunctionsTemplate + `
`
